// generated by ChapGPT and modified by Andy Modla
// cannot find import cc.cansik.opencv.OpenCV;

import gab.opencv.*;
import org.opencv.core.Mat;
import org.opencv.calib3d.StereoBM;
import org.opencv.core.CvType;
import org.opencv.calib3d.StereoSGBM;
import org.opencv.videoio.VideoCapture;

OpenCV opencv;
VideoCapture cap;
Mat frame;

PImage img;
int device_count;
boolean next = true;

void setup() {
  size(640, 480);
  background(128);
  textSize(48);
  fill(0);
  opencv = new OpenCV(this, 640, 480);
  device_count = 2;
  frame = new Mat();
}

void draw() {
  background(128);
  if ( next ) {
    println("check device_count="+device_count);
    cap = new VideoCapture(device_count);
    next = false;
  }
  //println("got it "+device_count);
  if (cap.read(frame) ) {
    PImage left = createImage(frame.width(), frame.height(), RGB);
    opencv.toPImage(frame, left);
    image(left, 0, 0, width, height);
    text("Camera # "+device_count, 100, 100);
  } else {
    text("No Image Camera #"+device_count, 100, 100);
  }
}

void keyPressed() {
  if (key == ' ') {
    println("space next camera");
    device_count++;
    next = true;
  }
}
